movies/urls.py
from django.conf.urls import url
from movies import views


app_name = 'movies'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<movie_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^add_movie/$', views.add_movie.as_view(), name='add_movie'),
    url(r'^(?P<movie_id>[0-9]+)/add_cast/$', views.add_cast, name='add_cast'),
    url(r'^(?P<movie_id>[0-9]+)/add_trivia/$', views.add_trivia, name='add_trivia'),
    url(r'^(?P<movie_id>[0-9]+)/delete_cast/(?P<cast_id>[0-9]+)/$',
        views.delete_cast, name='delete_cast'),
    url(r'^(?P<movie_id>[0-9]+)/update_cast/$',
        views.update_cast, name='update_cast'),
    url(r'^(?P<movie_id>[0-9]+)/delete_trivia/(?P<trivia_id>[0-9]+)/$',
        views.delete_trivia, name='delete_trivia'),
    url(r'^(?P<pk>[0-9]+)/update_movie/$', views.update_movie.as_view(), name='update_movie'),
    url(r'^(?P<movie_id>[0-9]+)/delete_movie/$', views.delete_movie, name='delete_movie'),
]

webSite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^movies/', include('movies.urls')),
    url(r'^', include('movies.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Movie(models.Model):
    director = models.CharField(max_length=250)
    movie_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    movie_art = models.FileField(blank=True)

    def __str__(self):
        return self.movie_title + ' - ' + self.director

    def get_absolute_url(self):
        return reverse('movies:detail', kwargs={'movie_id': self.pk})


class Cast(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    role = models.CharField(max_length=250)
    cast_name = models.CharField(max_length=250)

    def __str__(self):
        return self.cast_name

    def get_absolute_url(self):
        return reverse('movies:detail', kwargs={'cast_id': self.pk})


class Trivia(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    trivia_details = models.TextField(max_length=1000)

    def __str__(self):
        return self.trivia
        pass

movies/forms.py
from django import forms
from .models import Movie, Cast, Trivia


class MovieForm(forms.ModelForm):

    class Meta:
        model = Movie
        fields = ['director', 'movie_title', 'genre', 'movie_art']


class CastForm(forms.ModelForm):

    class Meta:
        model = Cast
        fields = ['role', 'cast_name']


class TriviaForm(forms.ModelForm):

    class Meta:
        model = Trivia
        fields = ['trivia_details']

movies/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from .forms import CastForm, TriviaForm
from .models import Movie, Cast, Trivia
from django.views.generic.edit import CreateView, UpdateView


class add_movie(CreateView):
    model = Movie
    fields = ['director', 'movie_title', 'genre', 'movie_art']
    template_name = 'movies/add_movie.html'


class update_movie(UpdateView):
    model = Movie
    fields = ['director', 'movie_title', 'genre', 'movie_art']
    template_name = 'movies/update_movie.html'


def add_cast(request, movie_id):
    form = CastForm(request.POST or None)
    movie = get_object_or_404(Movie, pk=movie_id)
    if form.is_valid():
        movies_casts = movie.cast_set.all()
        for s in movies_casts:
            if s.cast_name == form.cleaned_data.get("cast_name"):
                context = {
                    'movie': movie,
                    'form': form,
                    'error_message': 'You already added this cast',
                }
                return render(request, 'movies/add_cast.html', context)
        cast = form.save(commit=False)
        cast.movie = movie
        cast.save()
        return render(request, 'movies/detail.html', {'movie': movie})
    context = {
        'movie': movie,
        'form': form,
    }
    return render(request, 'movies/add_cast.html', context)


def update_cast(request, movie_id, template_name='update_cast.html'):
    form = CastForm(request.POST or None)
    movie = get_object_or_404(Movie, pk=movie_id)

    if request.POST and form.is_valid():
        form.save()

        # Save was successful, so redirect to another page
        redirect_url = reverse('movies/detail.html')
        return redirect(redirect_url)

    return render(request, 'movies/update_cast.html', {
        'movie': movie,
        'form': form,
    })


def add_trivia(request, movie_id):
    form = TriviaForm(request.POST or None)
    movie = get_object_or_404(Movie, pk=movie_id)
    if form.is_valid():
        movies_trivias = movie.trivia_set.all()
        for t in movies_trivias:
            if t.trivia_details == form.cleaned_data.get("trivia_details"):
                context = {
                    'movie': movie,
                    'form': form,
                    'error_message': 'You already added this cast',
                }
                return render(request, 'movies/add_trivia.html', context)
        cast = form.save(commit=False)
        cast.movie = movie
        cast.save()
        return render(request, 'movies/detail.html', {'movie': movie})
    context = {
        'movie': movie,
        'form': form,
    }
    return render(request, 'movies/add_trivia.html', context)


def delete_movie(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    movie.delete()
    return render(request, 'movies/index.html')


def delete_cast(request, movie_id, cast_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    cast = Cast.objects.get(pk=cast_id)
    cast.delete()
    return render(request, 'movies/detail.html', {'movie': movie})


def delete_trivia(request, movie_id, trivia_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    trivia = Trivia.objects.get(pk=trivia_id)
    trivia.delete()
    return render(request, 'movies/detail.html', {'movie': movie})


def detail(request, movie_id):

    movie = get_object_or_404(Movie, pk=movie_id)
    return render(request, 'movies/detail.html', {'movie': movie})


def index(request):

    movies = Movie.objects.filter()
    return render(request, 'movies/index.html', {'movies': movies})

movies/templates/movies/add_cast.html
{% extends 'movies/base.html' %}
{% block title %}Add Cast{% endblock %}
{% block movies_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Cast Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'movies:detail' movie.id %}">
                            {% if movie.movie_art %}
                                <img src="{{ movie.movie_art.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ movie.movie_title }} <small>{{ movie.genre }}</small></h1>
                    <h2>{{ movie.director }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Cast Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'movies:detail' movie.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'movies:add_cast' movie.id %}">Add Cast</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add Cast</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="movie" value="{{ movie }}">
                        {% include 'movies/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Add</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

movies/templates/movies/add_movie.html
{% extends 'movies/base.html' %}
{% block title %}Add a New Movie{% endblock %}
{% block movies_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Movie</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post"">
                        {% csrf_token %}
                        {% include 'movies/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

movies/templates/movies/add_trivia.html
{% extends 'movies/base.html' %}
{% block title %}Add Trivia{% endblock %}
{% block movies_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Cast Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'movies:detail' movie.id %}">
                            {% if movie.movie_art %}
                                <img src="{{ movie.movie_art.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ movie.movie_title }} <small>{{ movie.genre }}</small></h1>
                    <h2>{{ movie.director }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Cast Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'movies:detail' movie.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'movies:add_cast' movie.id %}">Add Trivia</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add Trivia</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="movie" value="{{ movie }}">
                        {% include 'movies/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Add</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

movies/templates/movies/base.html
<!DOCTYPE html>
<html>
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'movies/main.css' %}"/>
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

</head>
<body>

<div class="container-fluid" style="background-color:#F44336;color:#fff;height:200px;">
  <h1>Movie & Trivia Record</h1>
  <h3>Mohammed Jamal Hayder</h3>
  <p>s287771</p>
  <p>In this website You will be albe to keep record of movies along with its casts and trivias.</p>
</div>

<nav class="navbar navbar-inverse" data-spy="" data-offset-top="197">
  <ul class="nav navbar-nav">
    <li><a href="{% url 'movies:index' %}">Home</a></li>
    <li><a href="{% url 'movies:add_movie' %}">Add a Movie</a></li>

  </ul>
</nav>

<div class="container-fluid" style="height:1000px">
  
  {% block body %}
  {% endblock %}
</div>

</body>
</html>

movies/templates/movies/casts.html
{% extends 'movies/base.html' %}
{% block title %}All Cast{% endblock %}
{% block songs_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12">

        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Cast Name</th>
                                <th>Role</th>
                                <th>Movie</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for cast in cast_list %}
                                <tr>
                                    <td>{{ cast.cast_name }}</td>
                                    <td>{{ cast.movie }}</td>
                                    <td>
                                        <a href="{% url 'detail' cast.movie.id %}">
                                            <img src="{{ cast.movie.movie_art.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'detail' cast.movie.id %}">{{ cast.movie.movie_title }}</a>
                                    </td>

                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}

movies/templates/movies/detail.html
{% extends 'movies/base.html' %}
{% block title %}{{ movie }}{% endblock %}
{% block movies_active %}active{% endblock %}

{% block body %}
<div class="container-fluid casts-container">

    <div class="row">

        <!-- Left Movie Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'movies:detail' movie.id %}">
                        {% if movie.movie_art %}
                        <img src="{{ movie.movie_art.url }}" class="img-responsive">
                        {% else %}
                        <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ movie.movie_title }} <small>{{ movie.genre }}</small></h1>
                    <h2>{{ movie.director }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Cast Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'movies:detail' movie.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'movies:add_cast' movie.id %}">Add Cast</a></li>
                <li role="presentation"><a href="{% url 'movies:add_trivia' movie.id %}">Add Trivia</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Casts</h3>

                    {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Role</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for cast in movie.cast_set.all %}
                            <tr>
                                <td>{{ cast.cast_name }}</td>
                                <td>{{ cast.role}}</td>

                                <td>
                                    <form action="{% url 'movies:delete_cast' movie.id cast.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="movie_id" value="{{ movie.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Remove
                                        </button>
                                    </form>

                                </td>

                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>Trivia</h3>

                    {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                            <tr>
                                <th>Details</th>

                            </tr>
                        </thead>
                        <tbody>
                            {% for trivia in movie.trivia_set.all %}
                            <tr>
                                <td>{{ trivia.trivia_details }}</td>


                                <td>
                                    <form action="{% url 'movies:delete_trivia' movie.id trivia.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="trivia_id" value="{{ trivia.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Remove
                                        </button>
                                    </form>
                                </td>

                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

movies/templates/movies/form_template.html
{% for field in form %}
   <div class="form-group">
       <div class="col-sm-offset-2 col-sm-10">
           <span class="text-danger small">{{ field.errors }}</span>
       </div>
       <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
       <div class="col-sm-10">{{ field }}</div>
   </div>
{% endfor %}

movies/templates/movies/index.html
{% extends 'movies/base.html' %}
{% block movies_active %}active{% endblock %}

{% block body %}
<div class="movies-container container-fluid">

    <!-- Movies -->
    <div class="row">
        <div class="col-sm-12">
            <h3> Movies</h3>
        </div>
        {% if movies %}
            {% for movie in movies %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'movies:detail' movie.id %}">
                            <img src="{{ movie.movie_art.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ movie.movie_title }}</h2>
                            <h4>{{ movie.director }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'movies:detail' movie.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Movie -->
                            <form action="{% url 'movies:delete_movie' movie.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="movie_id" value="{{ movie.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                            <!-- Update Movie -->
                            <form action="{% url 'movies:update_movie' movie.id  %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="movie_id" value="{{ movie.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </button>
                            </form>


                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'movies:add_movie' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Movie
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    {% if casts %}
            <div class="row">
                <div class="col-sm-12">
                    <h3>Casts</h3>
                </div>
                <div class="col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Cast Name</th>
                                        <th>Artist</th>
                                        <th>Audio File</th>
                                        <th>Album</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    {% for cast in casts %}
                                        <tr>
                                            <td>{{ cast.movie_title }}</td>
                                            <td>{{ cast.movie.artist }}</td>

                                            <td>
                                                <a href="{% url 'movies:detail' cast.movie.id %}">
                                                    <img src="{{ cast.movie.movie_art.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                                </a>
                                                <a href="{% url 'movies:detail' cast.movie.id %}">{{ cast.movie.movie_title }}</a>
                                            </td>

                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}

    </div>
{% endblock %}

movies/templates/movies/trivia.html
{% extends 'movies/base.html' %}
{% block title %}Trivia{% endblock %}
{% block casts_active %}active{% endblock %}

{% block body %}
<div class="container-fluid casts-container">

    <div class="row">
        <div class="col-sm-12">

        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Details</th>


                            </tr>
                        </thead>
                        <tbody>
                            {% for cast in trivia_list %}
                                <tr>
                                    <td>{{ trivia.trivia }}</td>

                                    <td>
                                        <a href="{% url 'movies:detail' trivia.movie.id %}">
                                            <img src="{{ trivia.movie.movie_art.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'movies:detail' trivia.movie.id %}">{{ trivia.movie.movie_title }}</a>
                                    </td>

                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}

movies/templates/movies/update_cast.html
{% extends 'movies/base.html' %}
{% block title %}Update Cast{% endblock %}
{% block movies_active %}active{% endblock %}

{% block body %}


        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'movies:detail' movie.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'movies:add_cast' movie.id %}">Add Cast</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Update Cast</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="movie" value="{{ movie }}">
                        {% include 'movies/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

movies/templates/movies/update_movie.html
{% extends 'movies/base.html' %}
{% block title %}Update this Movie{% endblock %}
{% block movies_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Update this movie</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'movies/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}